# Generated by Django 2.1.3 on 2018-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datauiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='phone1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='phone4',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
