# Generated by Django 2.1.3 on 2018-11-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datauiapp', '0002_auto_20181125_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(blank=True, max_length=256)),
                ('firm_file_number', models.CharField(blank=True, max_length=256)),
                ('court_case_number', models.CharField(blank=True, max_length=256)),
                ('doi', models.DateTimeField()),
                ('criticalnote', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='TestModel',
            new_name='ClientModel',
        ),
        migrations.AddField(
            model_name='casemodel',
            name='caseclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datauiapp.ClientModel'),
        ),
    ]
